# Generated by Django 4.2.2 on 2023-06-21 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('instructor_name', models.CharField(max_length=255)),
                ('instructor_description', models.CharField(max_length=10000)),
                ('instructor_qualification', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='123', max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('working_status', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='student_academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField(blank=True, null=True)),
                ('college_university', models.TextField(blank=True, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
            options={
                'db_table': 'student_academics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
                ('course_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('course_description', models.TextField(blank=True, db_column='course_Description', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('students_enrolled', models.IntegerField(blank=True, null=True)),
                ('course_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, db_column='Prerequisites', null=True)),
                ('learning_outcomes', models.TextField(blank=True, null=True)),
                ('course_context', models.TextField(blank=True, null=True)),
                ('instructor_id', models.ManyToManyField(to='dashboard.instructor')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentOptedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('attendance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drive_link', models.TextField(blank=True, null=True)),
                ('course_status', models.CharField(blank=True, max_length=9, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
            options={
                'db_table': 'student_opted_courses',
                'managed': True,
                'unique_together': {('student_id', 'course_id')},
            },
        ),
    ]
