# Generated by Django 4.0.3 on 2023-05-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_description',
            field=models.CharField(max_length=10000),
        ),
    ]
