# Generated by Django 4.2.2 on 2023-06-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_banner', models.TextField(blank=True, null=True)),
                ('speaker_image', models.TextField(blank=True, null=True)),
                ('event_link', models.TextField(blank=True, null=True)),
                ('event_description', models.CharField(blank=True, max_length=255, null=True)),
                ('event_speaker', models.CharField(max_length=255)),
                ('speaker_description', models.CharField(max_length=255)),
                ('event_startdatetime', models.DateTimeField()),
                ('event_enddatetime', models.DateTimeField()),
                ('event_duration', models.TextField()),
                ('event_venue', models.TextField()),
                ('event_mode', models.CharField(max_length=255)),
                ('students_enrolled', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('event_fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Event',
                'managed': True,
            },
        ),
    ]
