# Generated by Django 4.0.3 on 2023-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_instructor_instructor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
