# Generated by Django 4.2.2 on 2023-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_event_event_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_duration',
            field=models.TimeField(),
        ),
    ]
