# Generated by Django 4.2.2 on 2023-06-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_course_context_course_course_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_banner', models.TextField(blank=True, null=True)),
                ('speaker_image', models.TextField(blank=True, null=True)),
                ('event_link', models.TextField(blank=True, null=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.CharField(blank=True, max_length=255, null=True)),
                ('event_speaker', models.CharField(max_length=255)),
                ('event_duration', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_mode', models.CharField(max_length=7)),
                ('students_enrolled', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('registration_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='event_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.event')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
