# Generated by Django 4.2.2 on 2023-06-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.event')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
            options={
                'db_table': 'event_registeration',
                'managed': True,
            },
        ),
    ]
