# Generated by Django 4.2.2 on 2023-06-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_event_event_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_datetime',
        ),
    ]
