# Generated by Django 4.2.2 on 2023-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_event_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
    ]
