# Generated by Django 4.2.2 on 2023-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Past', 'Past'), ('Live', 'Live'), ('Upcoming', 'Upcoming')], default='past', max_length=255),
            preserve_default=False,
        ),
    ]
