# Generated by Django 4.2.2 on 2023-06-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Past', 'Past'), ('Live', 'Live'), ('Upcoming', 'Upcoming')], max_length=255, null=True),
        ),
    ]
