# Generated by Django 4.2.2 on 2023-06-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_event_is_past'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_price',
            new_name='event_fees',
        ),
    ]
