# Generated by Django 4.0.3 on 2023-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_course_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
