# Generated by Django 4.2.2 on 2023-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_event_date_event_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
