# Generated by Django 4.2.2 on 2023-06-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.TextField(default='IIITD'),
            preserve_default=False,
        ),
    ]
