# Generated by Django 4.2.2 on 2023-06-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_event_event_venue'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event_registration',
            table='Event_registeration',
        ),
    ]
