# Generated by Django 4.2.2 on 2023-06-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_event_event_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event_registration',
            unique_together={('event_id', 'student_id')},
        ),
    ]
