# Generated by Django 4.2.2 on 2023-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_event_registration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker_description',
            field=models.TextField(),
        ),
    ]
