# Generated by Django 4.2.2 on 2023-06-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_event_registration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event_registration',
            table='Event_registration',
        ),
    ]
