# Generated by Django 4.2.2 on 2023-06-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_event_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='interns',
            fields=[
                ('intern_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('intern_name', models.CharField(max_length=255)),
                ('intern_description', models.TextField()),
                ('intern_qualification', models.TextField()),
            ],
            options={
                'db_table': 'Intern',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='techteam',
            fields=[
                ('techteam_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('techteam_name', models.CharField(max_length=255)),
                ('techteam_description', models.TextField()),
                ('techteam_qualification', models.TextField()),
            ],
            options={
                'db_table': 'Techteam',
                'managed': True,
            },
        ),
    ]
