# Generated by Django 4.2.2 on 2023-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_interns_techteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.CharField(default='TBD', max_length=255),
            preserve_default=False,
        ),
    ]
