# Generated by Django 4.2.2 on 2023-06-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_course_certification_criteria_alter_course_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('executives_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('executives_name', models.CharField(max_length=255)),
                ('executives_description', models.TextField()),
                ('executives_qualification', models.TextField()),
            ],
            options={
                'db_table': 'Executives',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='interns',
            new_name='Intern',
        ),
    ]
