# Generated by Django 4.2.2 on 2023-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='event_source',
            field=models.TextField(choices=[('online', 'Online advertisement'), ('friends', 'Word of mouth from friends'), ('social_media', 'Social media'), ('poster', 'Poster or flyer'), ('email', 'Email newsletter'), ('other', 'Other')], default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_registration',
            name='previous_event',
            field=models.TextField(default='sfg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_registration',
            name='previous_knowledge',
            field=models.TextField(default='sfsf'),
            preserve_default=False,
        ),
    ]
