# Generated by Django 4.2.2 on 2023-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_event_registration_event_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_registration',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='event_source',
            field=models.TextField(blank=True, choices=[('online', 'Online advertisement'), ('friends', 'Word of mouth from friends'), ('social_media', 'Social media'), ('poster', 'Poster or flyer'), ('email', 'Email newsletter'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='previous_event',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='previous_knowledge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
