# Generated by Django 4.2.2 on 2023-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_event_registration_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='event_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
