# Generated by Django 4.2.2 on 2023-07-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techteam',
            old_name='techteam_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='techteam',
            old_name='techteam_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='techteam',
            old_name='techteam_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='techteam',
            old_name='techteam_qualification',
            new_name='qualification',
        ),
    ]
