# Generated by Django 4.2.2 on 2023-07-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_techteam_description_techteam_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='techteam',
            new_name='Techteam_mem',
        ),
        migrations.AlterModelTable(
            name='techteam_mem',
            table='Techteam_mem',
        ),
    ]
