# Generated by Django 4.2.2 on 2023-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_techteam_techteam_mem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='linkdln',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
