# Generated by Django 4.2.2 on 2023-07-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_instructor_linkdln_instructor_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='linkdln',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techteam_mem',
            name='linkdln',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
