# Generated by Django 4.2.2 on 2023-07-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_executive_linkdln_techteam_mem_linkdln'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='executive',
            table='Executive',
        ),
    ]
