# Generated by Django 4.2.2 on 2023-07-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_executive_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='executive',
            table='Executive_team',
        ),
    ]
