# Generated by Django 4.2.2 on 2023-07-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_executive_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executive',
            new_name='Executive_team',
        ),
    ]
